# Generated by Django 4.0.8 on 2023-04-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_categroy_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='categroy',
            new_name='category',
        ),
    ]
